config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do 
    resources :pets, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  devise_scope :user do
     authenticated :user do
       root 'pets#index', as: :authenticated_root
     end
     unauthenticated do
       root 'devise/sessions#new', as: :unauthenticated_root
     end
   end

  get '/api/pets/:id' => 'pets#pet'
  get '/api/owner/:id' => 'pets#owner'
  get '/api/image/:id' => 'pets#image'

end

app/models/pet.rb
class Pet < ActiveRecord::Base

  has_attached_file :image, styles: { logo: "50x50>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, :species,  presence: true
  validates :age, numericality: {only_integer: true, greater_than: -1}

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  
  has_many :pets       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
      end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :authenticate_user!

  def index    
      @pets = Pet.all
  end

  def new
    @user = current_user
    @pet = current_user.pets.new
  end

  def create
    @user = current_user
    @pet = current_user.pets.new(pet_params)
    if @pet.save
      flash[:notice] = 'You have a new pet!'
      redirect_to(user_pets_path)
    else
      flash[:alert] = "Pet couldn't be saved"
      @errors = @pet.errors.full_messages
      render 'new'
    end
  end

  def edit
    @user = current_user
    @pet = Pet.find(params[:id]) 
  end

  def update
    @user = current_user
    @pet = Pet.find(params[:id])
    if @pet.update_attributes(pet_params)
      flash[:notice] = "Pet updated!"
      redirect_to(user_pets_path)
    else
      flash[:alert] = "Pet couldn´t be updated"
      @errors = @pet.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    flash[:notice] = "Pet deleted"
    redirect_to(user_pets_path)
  end

  def pet
    pet = Pet.find_by_id(params[:id])
    render status:200,json:pet
  end

  def owner
    pet = Pet.find_by_id(params[:id])
    owner = pet.user
    render status:200,json:owner
  end

  def image
     pet = Pet.find_by_id(params[:id])
     image_url = pet.image.url
     render status:200, json:{url:image_url}
   end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groopify</title>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>  

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>

<header>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3">
        <a href="/">
          <img class="logo" src="/logo.png" height="50">
        </a>  
      </div>

      <div class="col-xs-12 col-md-5 notices">      
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <div class="col-xs-12 col-md-4 nav-bar">
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.name %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>

      </div>
    </div>
  </div>
</header>


<section class="body-content">
  <div class="container">  
    <div class="row">
      <div class="col-xs-12 col-md-12">      
        <%= yield %>
      </div>
    </div>
  </div>
</section>


<footer>
  Raul Villalonga Palliser  
</footer>

</body>
</html>

app/views/pets/_form.html.erb
<section id="pets-form">
  <%= form_for [@user, @pet], html: { class: "form-horizontal" } do |f| %>

  <div class="form-group">
    <%= f.label :name, class:'col-sm-2 control-label' %>
    <div class="col-sm-4">
    <%= f.text_field :name, class:'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :species, class:'col-sm-2 control-label' %>
    <div class="col-sm-4">
    <%= f.text_field :species, class:'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age, class:'col-sm-2 control-label' %>
    <div class="col-sm-4">
    <%= f.number_field :age, class:'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class:'col-sm-2 control-label' %>
    <div class="col-sm-4">
    <%= f.file_field :image, class:'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'save' , class:'btn btn-primary'%>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
          <%= link_to('Cancel',user_pets_path) %>
    </div>
  </div>
     


  <% end %>
</section>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6">    
    <h1>Listing Pets</h1>
  </div>
  <div class="col-xs-12 col-md-6">
    <h2><%= link_to '+ Add new pet', new_user_pet_path(current_user) %></h2>    
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.user.name %></td>
        <td><a href="/" class="js-show-details" data-pet="<%=pet.id%>">Details<a></td>
        <% if current_user.id == pet.user_id %>
          <td><%= link_to("Edit", edit_user_pet_path(current_user, pet)) %></td>
          <td><%= link_to('Delete', user_pet_path(current_user, pet), method: :delete, data: {confirm: 'Are you sure?'}) %></td>
        <%else%>
        <td></td>
        <td></td>
        <%end %>
        
      </tr>
    <% end %>
  </tbody>
</table>



<div class="modal fade js-pet-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>

        <h3 class="modal-title">
          <b><span>Name: </span></b>        
          <span class="js-pet-name">Name</span>
        </h3>
      </div>

      <div class="modal-body">
        <dl class="dl-horizontal">
          <dt>Species: </dt>
          <dd class="js-pet-species">Species</dd>
          <dt>Age: </dt>
          <dd class="js-pet-age">100</dd>
          <dt>Owner: </dt>
          <dd class="js-pet-owner">Owner</dd>
          <dt>Image: </dt>
          <img src="" class="js-pet-image" height="250">
        </dl>
      </div>

    </div>
  </div>
</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>